### ISSUE TITLE
Missing call to Wire.begin()

### ISSUE THREAD

**Issue by different55** [RCmags/basicMPU6050#1]
First of all, thanks for making this library! Smallest flash footprint of any MPU6050 library I've come across, especially when you're not making use of all the fancy floating point features. Just like as a size comparison, Adafruit's MPU6050 library, with nothing else, immediately blows clear through the ATTiny85's 8K and then some. This one is *barely* more than 1K, perfect for a constrained environment like that, so thanks!

Anyway, one issue I did run into when moving code from my Uno testing ground to its final home on the ATTiny85 was that a missing call to Wire.begin() anywhere in the library meant that all reads from the MPU failed and returned -1. Works just fine on the Uno but I guess the Wire library provided by the ATTinyCore I'm using is a little more picky. Also works fine if you manually slap a call to Wire.begin() in your own code before you start making calls into this library.

**Comment by RCmags** [comment]
Thanks for letting me know about this bug! I was concerned it might not work for other boards as I've only tested this on a Mega. I've added Wire.begin() to the setup function. Cheers.

**Comment by different55** [comment]
Thank you much!
