### ISSUE TITLE
need help regarding ubuntu

### ISSUE THREAD

**Issue by abdelalifihri** [RCmags/basicMPU6050#10]
Hi please I have an issue, I wanted to scrap Google results exactly to find the number of search results in excel, I found this source here https://github.com/RomainFallet/keyworder it is what I want, but it didn't work because of the commands (sudo npm install
, sudo npm install puppeteer@1.13.0 --unsafe-perm=true --allow-root --no-save, npm run build). 
Please let me know how to solve this problem.

**Comment by RCmags** [comment]
Hi,
Ummm... I'm not sure what this has to do with this arduino library. Imma close this. Cheers.
