### ISSUE TITLE
Hardcoded (not always correct) I2C address

### ISSUE THREAD

**Issue by gitcnd** [RCmags/basicMPU6050#4]
Many people tie AD0 to VCC to change the I2C address to 0x69 because the default 0x68 address conflicts with most RTC boards (e.g. https://wiki.seeedstudio.com/Pi_RTC-DS1307/ ) ... which makes this library useless, because you forgot to let us pass in the I2C address during init...

**Comment by gitcnd** [comment]
It's probably also a bad idea to omit allowing us to change the I2C SCL and SDA pins, for what it's worth...

**Comment by RCmags** [comment]
Hi! Thanks for mentioning this. I'll include these features as soon as I can.

**Comment by RCmags** [comment]
Added an input to change the I2C address. See latest version. SCL and SDA are still fixed though.
