### ISSUE TITLE
 same values diffrent mpus

### ISSUE THREAD

**Issue by Mulluchtschi** [RCmags/basicMPU6050#8]
Hello, I get the same values for both although both MPU's are connected to different addresses and are read out individually.What is wrong with my code?

#include <Wire.h>
#include <basicMPU6050.h> 

#define MPU_ADDRESS_LOW  0x68                
#define MPU_ADDRESS_HIGH 0x69

basicMPU6050<MPU_ADDRESS_LOW> imu1;
basicMPU6050<MPU_ADDRESS_HIGH> imu2;

void setup() {

  Wire.begin();
  Serial.begin(38400);

  Wire.beginTransmission(MPU_ADDRESS_LOW);
  Wire.write(0x6B); // PWR_MGMT_1 register
  Wire.write(0x00); // set to zero (wake up MPU6050)
  Wire.endTransmission();

  Wire.beginTransmission(MPU_ADDRESS_HIGH);
  Wire.write(0x6B); // PWR_MGMT_1 register
  Wire.write(0x00); // set to zero (wake up MPU6050)
  Wire.endTransmission();
 
  Wire.beginTransmission(MPU_ADDRESS_LOW);
  if (Wire.endTransmission() == 0) {
    Serial.println("MPU6050 IMU 1 connected.");
  } else {
    Serial.println("MPU6050 IMU 1 NOT connected!");
  }

  Wire.beginTransmission(MPU_ADDRESS_HIGH);
  if (Wire.endTransmission() == 0) {
    Serial.println("MPU6050 IMU 2 connected.");
  } else {
    Serial.println("MPU6050 IMU 2 NOT connected!");
  }

  imu1.setBias();
  imu2.setBias();
}

void loop() { 

  imu1.updateBias(); 

  Serial.print( imu1.ax() );
  Serial.print( " " );
  Serial.print( imu1.ay() );
  Serial.print( " " );
  Serial.print( imu1.az() );
  Serial.print( " " );
  
  imu2.updateBias();
 
  Serial.print( imu2.ax() );
  Serial.print( " " );
  Serial.print( imu2.ay() );
  Serial.print( " " );
  Serial.print( imu2.az() );
  Serial.println();  

  delay(100);
}

**Comment by RCmags** [comment]
Hi!
At a glance, your problem lay in not having configured the imu's correctly. On the lines:

```c++
basicMPU6050<MPU_ADDRESS_LOW> imu1;
basicMPU6050<MPU_ADDRESS_HIGH> imu2;
```
You must provide aditional inputs to configure the I2C address. See the example sketch "parameters". In your case, this would be:

```c++
// Gyro settings:
#define         LP_FILTER   3           // Low pass filter.                    Value from 0 to 6
#define         GYRO_SENS   0           // Gyro sensitivity.                   Value from 0 to 3
#define         ACCEL_SENS  0           // Accelerometer sensitivity.          Value from 0 to 3
#define         ADDRESS_A0  LOW         // I2C address from state of A0 pin.   A0 -> GND : ADDRESS_A0 = LOW

basicMPU6050<LP_FILTER,  GYRO_SENS,  ACCEL_SENS, ADDRESS_A0> imu;
```
Let me know if this fixed your problem.
