### ISSUE TITLE
basicMPU6050 with ESP32

### ISSUE THREAD

**Issue by MohamedGaberZidan** [RCmags/basicMPU6050#9]
Hello,

I'm trying to run basicMPU6050 with ESP32, but I got some errors, hope you can help me with that.
Firstly, for Velocity example, esp32 keep resetting. I tried to debug it and I think this error because of vector data type library. 
Secondly, For output example. The readings are not stable at all and keep changes although I didn't move the module at all.

Sorry for your time, I will be very grateful if you can help me. Thanks in advance.

Sincerely,
Zidan

**Comment by RCmags** [comment]
Hi Zidan,

I'm a little confused when you mention vector_datatype. This library does not depend on it. Are you refering to the velocity example from [imuFilter](https://github.com/RCmags/imuFilter)?

As for the output example: 
- Is your MPU wired correctly to the ESP32? Check whether the SCL and SCA pins are not swapped. 
- Do you have another MPU6050 that you can test? Try connecting it instead
- Try a different sensor library. Can you get a stable output with, for example, [tockn's library](https://github.com/tockn/MPU6050_tockn)?
- Do you have any compilation errors?

**Comment by RCmags** [comment]
We'll need to continue from here, after testing vector_datatype. Please answer the questions I asked before. Thanks. 

In particular, please test tockn's library or some alternative, and provide any compilation errors. That way we can be sure your sensor is working.

**Comment by MohamedGaberZidan** [comment]
I think it works well
02:26:44.219 -> =======================================================
02:26:44.253 -> temp : 30.67
02:26:44.287 -> accX : 1.01	accY : 0.01	accZ : 0.07
02:26:44.321 -> gyroX : -0.07	gyroY : 0.10	gyroZ : 0.12
02:26:44.355 -> accAngleX : 0.80	accAngleY : -85.91
02:26:44.388 -> gyroAngleX : 14.16	gyroAngleY : -0.20	gyroAngleZ : -0.39
02:26:44.456 -> angleX : 0.32	angleY : -85.89	angleZ : -0.39
02:26:44.524 -> =======================================================
02:26:44.558 -> 
02:26:45.439 -> =======================================================
02:26:45.507 -> temp : 30.76
02:26:45.507 -> accX : 1.01	accY : 0.01	accZ : 0.07
02:26:45.540 -> gyroX : -0.13	gyroY : 0.08	gyroZ : 0.07
02:26:45.608 -> accAngleX : 0.66	accAngleY : -85.79
02:26:45.643 -> gyroAngleX : 14.00	gyroAngleY : -0.10	gyroAngleZ : -0.40
02:26:45.711 -> angleX : 0.35	angleY : -85.94	angleZ : -0.40
02:26:45.745 -> =======================================================
02:26:45.813 -> 
02:26:46.659 -> =======================================================
02:26:46.727 -> temp : 30.81
02:26:46.727 -> accX : 1.02	accY : 0.01	accZ : 0.07
02:26:46.795 -> gyroX : 0.02	gyroY : 0.08	gyroZ : -0.05
02:26:46.828 -> accAngleX : 0.48	accAngleY : -86.05
02:26:46.862 -> gyroAngleX : 13.95	gyroAngleY : -0.04	gyroAngleZ : -0.35
02:26:46.930 -> angleX : 0.27	angleY : -85.98	angleZ : -0.35

**Comment by RCmags** [comment]
Ok, so this is tockn's library, no? 

Since the arduino can communicate succesfully with the MPU6050, as shown by these results, try the basicMPU6050 library. Use the example "output". Ideally, you should get the values for the gyroscope (in radians/second) and accelerometer (in g-unit). Please report the console output.

**Comment by MohamedGaberZidan** [comment]
I think it's working well too. 
03:27:52.573 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.573 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.607 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.91
03:27:52.607 -> 0.99 3.98 0.21    4.73 -0.09 0.11    222.91
03:27:52.607 -> 0.99 3.98 0.21    4.73 -0.09 0.11    222.90
03:27:52.640 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.640 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.640 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.675 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.675 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.90
03:27:52.675 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.89
03:27:52.708 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.89
03:27:52.708 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.89
03:27:52.741 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.89
03:27:52.741 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.89
03:27:52.741 -> 0.99 3.98 0.21    -4.00 -0.09 0.11    222.89

The problem appears with IMU filter for vector_output example
= 0.94,-0.22,0.24 | y = 0.11,0.90,0.41 | z = -0.31,-0.37,0.88 | v = 1.05,0.68,0.66 | q = -0.97,-0.20,0.14,0.08
03:29:28.722 ->  x = 0.94,-0.22,0.24 | y = 0.12,0.92,0.38 | z = -0.31,-0.33,0.89 | v = 1.06,0.70,0.62 | q = -0.97,-0.18,0.14,0.09
03:29:28.755 ->  x = 0.94,-0.22,0.24 | y = 0.13,0.93,0.34 | z = -0.30,-0.29,0.91 | v = 1.08,0.71,0.58 | q = -0.97,-0.16,0.14,0.09
03:29:28.790 ->  x = 0.94,-0.22,0.24 | y = 0.06,0.85,0.53 | z = -0.32,-0.48,0.81 | v = 1.01,0.63,0.77 | q = -0.95,-0.27,0.15,0.07
03:29:28.823 ->  x = 0.94,-0.22,0.24 | y = 0.08,0.87,0.49 | z = -0.32,-0.45,0.84 | v = 1.02,0.65,0.74 | q = -0.95,-0.25,0.15,0.08
03:29:28.857 ->  x = 0.94,-0.22,0.24 | y = 0.09,0.88,0.46 | z = -0.32,-0.41,0.86 | v = 1.03,0.66,0.70 | q = -0.96,-0.23,0.15,0.08
03:29:28.892 ->  x = 0.94,-0.22,0.24 | y = 0.10,0.90,0.42 | z = -0.31,-0.37,0.87 | v = 1.05,0.68,0.66 | q = -0.96,-0.21,0.14,0.08
03:29:28.892 ->  x = 0.94,-0.22,0.24 | y = 0.12,0.92,0.38 | z = -0.31,-0.33,0.89 | v = 1.06,0.70,0.63 | q = -0.97,-0.19,0.14,0.09
03:29:28.927 ->  x = 0.94,-0.22,0.24 | y = 0.13,0.93,0.35 | z = -0.30,-0.29,0.91 | v = 1.07,0.71,0.59 | q = -0.97,-0.16,0.14,0.09
03:29:28.961 ->  x = 0.94,-0.22,0.24 | y = 0.14,0.94,0.31 | z = -0.30,-0.26,0.92 | v = 1.09,0.72,0.55 | q = -0.98,-0.14,0.14,0.09
03:29:28.997 ->  x = 0.94,-0.22,0.24 | y = 0.15,0.95,0.27 | z = -0.29,-0.21,0.93 | v = 1.10,0.73,0.51 | q = -0.98,-0.12,0.14,0.10
03:29:29.030 ->  x = 0.94,-0.22,0.24 | y = 0.17,0.96,0.23 | z = -0.28,-0.17,0.94 | v = 1.11,0.74,0.47 | q = -0.98,-0.10,0.13,0.10
03:29:29.064 ->  x = 0.94,-0.22,0.24 | y = 0.18,0.97,0.19 | z = -0.28,-0.13,0.95 | v = 1.12,0.74,0.43 | q = -0.98,-0.08,0.13,0.10

and for velocity example it throws and exception error and makes my esp32 keep resetting

**Comment by RCmags** [comment]
Ok! That means we can discard this library as a cause for the problems. Lets move to the imuFilter issue.

**Comment by RCmags** [comment]
Sorry, I've checked the output again and something is wrong with your values. 

The first three numbers are the acceleration. These should be normalized with magnitude 1 with the sensor at rest. It's measuring 4-g about the y-axis. 
 0.99 3.98 0.21 

The next three are the gyroscope. The value of the x-axis is stuck at around 4 rad/s. This makes no sense if the sensor is static. It also explains why the imuFilter fails as its receiving a constant-rate rotation.
-4.00 -0.09 0.11 

The last is the temperature. Its much too high, and should read around 20-30 celcius. 
222.90

Were you holding the sensor still while taking these measurements?

**Comment by RCmags** [comment]
This may be a configuration problem. Try running the "parameters" example and provide the console output. Set the accelerometer offset's to 0, and set the scales for the acceleration and the gyro to 1.
